name: Find Platformio

on:
  push:
    branches:
    - master

jobs:
  release:
    name: Binary_Tracker_Release
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pio
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: find pio
      run: cd /home/runner/.platformio && ls && cd packages && ls
